CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN CREATE TYPE service_status AS ENUM ('draft','active','paused','archived'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE agreement_status AS ENUM ('draft','active','suspended','terminated','completed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE monitor_status AS ENUM ('active','paused','error'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE incident_status AS ENUM ('open','recovering','resolved','unknown'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE case_status AS ENUM ('open','evidence_locked','submitted','decided','appealable','appealed','finalized','settling','settled','closed','undetermined'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE adjudication_status AS ENUM ('submitted','pending','proposing','committing','revealing','accepted','appealable','appealed','ready_to_finalize','finalized','undetermined','failed','canceled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE settlement_status AS ENUM ('draft','authorized','dispatched','delivered','executing','executed','reconciling','settled','expired','failed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE protocol_kind AS ENUM ('ethereum','sealevel'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workos_organization_id text UNIQUE, name text NOT NULL, slug text NOT NULL UNIQUE, settings jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workos_user_id text NOT NULL UNIQUE, email text NOT NULL, display_name text, privy_user_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memberships (organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL DEFAULT 'member', permissions jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(organization_id,user_id));
CREATE TABLE IF NOT EXISTS wallets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE SET NULL, owner_type text NOT NULL, owner_id uuid, chain_family text NOT NULL, address text NOT NULL, provider text NOT NULL, purpose text NOT NULL DEFAULT 'general', verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS wallet_org_addr_uq ON wallets(organization_id,chain_family,address);
CREATE TABLE IF NOT EXISTS wallet_challenges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, chain_family text NOT NULL, address text NOT NULL, nonce text NOT NULL, message text NOT NULL, expires_at timestamptz NOT NULL, consumed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS api_keys (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, name text NOT NULL, prefix text NOT NULL, secret_hash text NOT NULL, permissions jsonb NOT NULL DEFAULT '[]'::jsonb, last_used_at timestamptz, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS services (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, name text NOT NULL, kind text NOT NULL DEFAULT 'api', description text, status service_status NOT NULL DEFAULT 'draft', visibility text NOT NULL DEFAULT 'private', base_url text, status_page_url text, documentation_url text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS services_org_idx ON services(organization_id);
CREATE TABLE IF NOT EXISTS service_credentials (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, service_id uuid NOT NULL REFERENCES services(id) ON DELETE CASCADE, name text NOT NULL, kind text NOT NULL, ciphertext text NOT NULL, key_version integer NOT NULL DEFAULT 1, rotated_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, name text NOT NULL, operator_user_id uuid REFERENCES users(id) ON DELETE SET NULL, description text, capabilities jsonb NOT NULL DEFAULT '[]'::jsonb, authority_policy jsonb NOT NULL DEFAULT '{}'::jsonb, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agent_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, agent_id uuid NOT NULL REFERENCES agents(id) ON DELETE CASCADE, agreement_id uuid, title text NOT NULL, input jsonb NOT NULL DEFAULT '{}'::jsonb, deliverable_hash text, status text NOT NULL DEFAULT 'pending', accepted_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agent_execution_receipts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, task_id uuid NOT NULL REFERENCES agent_tasks(id) ON DELETE CASCADE, receipt_type text NOT NULL, payload jsonb NOT NULL, payload_hash text NOT NULL, signature text, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS agreements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, service_id uuid REFERENCES services(id) ON DELETE SET NULL, agent_id uuid REFERENCES agents(id) ON DELETE SET NULL, name text NOT NULL, kind text NOT NULL, status agreement_status NOT NULL DEFAULT 'draft', current_version integer NOT NULL DEFAULT 1, settlement_route_key text, settlement_asset text, governed_value numeric(78,0), metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS agreements_org_idx ON agreements(organization_id);
CREATE TABLE IF NOT EXISTS agreement_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, agreement_id uuid NOT NULL REFERENCES agreements(id) ON DELETE CASCADE, version integer NOT NULL, terms jsonb NOT NULL, terms_hash text NOT NULL, policy_version integer NOT NULL DEFAULT 1, effective_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS agreement_version_uq ON agreement_versions(agreement_id,version);
CREATE TABLE IF NOT EXISTS agreement_parties (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, agreement_id uuid NOT NULL REFERENCES agreements(id) ON DELETE CASCADE, party_type text NOT NULL, party_id text NOT NULL, role text NOT NULL, settlement_address text NOT NULL, accepted_version integer, accepted_at timestamptz, signature text);

CREATE TABLE IF NOT EXISTS monitors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, service_id uuid NOT NULL REFERENCES services(id) ON DELETE CASCADE, name text NOT NULL, url text NOT NULL, method text NOT NULL DEFAULT 'GET', interval_seconds integer NOT NULL, timeout_ms integer NOT NULL, regions jsonb NOT NULL DEFAULT '[]'::jsonb, assertions jsonb NOT NULL DEFAULT '{}'::jsonb, credential_id uuid REFERENCES service_credentials(id) ON DELETE SET NULL, status monitor_status NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS incidents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, service_id uuid NOT NULL REFERENCES services(id) ON DELETE CASCADE, monitor_id uuid REFERENCES monitors(id) ON DELETE SET NULL, status incident_status NOT NULL DEFAULT 'open', classification text NOT NULL, severity text NOT NULL DEFAULT 'minor', started_at timestamptz NOT NULL, recovered_at timestamptz, summary text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, agreement_id uuid NOT NULL REFERENCES agreements(id) ON DELETE CASCADE, case_id uuid, kind text NOT NULL, source text NOT NULL, provenance jsonb NOT NULL, object_key text, sha256 text NOT NULL, content_type text, size_bytes bigint, verification_status text NOT NULL DEFAULT 'unverified', redaction_policy jsonb NOT NULL DEFAULT '{}'::jsonb, observed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS evidence_bundles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, agreement_id uuid NOT NULL REFERENCES agreements(id) ON DELETE CASCADE, manifest jsonb NOT NULL, manifest_hash text NOT NULL, locked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS evidence_bundle_items (bundle_id uuid NOT NULL REFERENCES evidence_bundles(id) ON DELETE CASCADE, evidence_id uuid NOT NULL REFERENCES evidence(id) ON DELETE CASCADE, ordinal integer NOT NULL, PRIMARY KEY(bundle_id,evidence_id));
CREATE TABLE IF NOT EXISTS tls_proofs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, evidence_id uuid NOT NULL REFERENCES evidence(id) ON DELETE CASCADE, proof_object_key text NOT NULL, proof_hash text NOT NULL, verifier_version text NOT NULL, disclosure_manifest jsonb NOT NULL DEFAULT '{}'::jsonb, verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS cases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, agreement_id uuid NOT NULL REFERENCES agreements(id) ON DELETE CASCADE, case_type text NOT NULL, status case_status NOT NULL DEFAULT 'open', claim text NOT NULL, requested_outcome text, evidence_bundle_id uuid REFERENCES evidence_bundles(id) ON DELETE SET NULL, opened_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS cases_org_idx ON cases(organization_id);
CREATE TABLE IF NOT EXISTS disputes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, case_id uuid NOT NULL UNIQUE REFERENCES cases(id) ON DELETE CASCADE, claimant_statement text, respondent_statement text, counterclaim text, response_due_at timestamptz, evidence_locked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS adjudications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, case_id uuid NOT NULL REFERENCES cases(id) ON DELETE CASCADE, resolver_key text NOT NULL, genlayer_contract text NOT NULL, genlayer_tx_hash text, status adjudication_status NOT NULL DEFAULT 'submitted', accepted_at timestamptz, appeal_deadline timestamptz, finalized_at timestamptz, execution_result text, raw_decision jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS appeals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, adjudication_id uuid NOT NULL REFERENCES adjudications(id) ON DELETE CASCADE, round integer NOT NULL, reason text NOT NULL, new_evidence_bundle_id uuid REFERENCES evidence_bundles(id) ON DELETE SET NULL, genlayer_tx_hash text, status text NOT NULL DEFAULT 'submitted', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS decisions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, case_id uuid NOT NULL REFERENCES cases(id) ON DELETE CASCADE, adjudication_id uuid NOT NULL REFERENCES adjudications(id) ON DELETE CASCADE, decision_hash text NOT NULL UNIQUE, outcome text NOT NULL, reason_code text NOT NULL, remedy_bps integer NOT NULL DEFAULT 0, liability jsonb NOT NULL DEFAULT '[]'::jsonb, finalized_at timestamptz NOT NULL, evidence_manifest_hash text NOT NULL, policy_version integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS chain_routes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key text NOT NULL UNIQUE, display_name text NOT NULL, protocol protocol_kind NOT NULL, chain_id text NOT NULL, domain_id integer NOT NULL, mailbox text NOT NULL, ism text, receiver text, escrow_contract text, rpc_env text NOT NULL, explorer text, enabled boolean NOT NULL DEFAULT true, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, last_health_check timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS escrows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, agreement_id uuid NOT NULL REFERENCES agreements(id) ON DELETE CASCADE, route_key text NOT NULL, asset text NOT NULL, asset_decimals integer NOT NULL, payer_address text NOT NULL, provider_address text NOT NULL, customer_address text NOT NULL, max_customer_remedy_bps integer NOT NULL DEFAULT 10000 CHECK (max_customer_remedy_bps BETWEEN 0 AND 10000), amount numeric(78,0) NOT NULL, remaining_amount numeric(78,0) NOT NULL, status text NOT NULL DEFAULT 'created', onchain_escrow_id text NOT NULL, funding_tx_hash text, funded_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS settlement_instructions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, decision_id uuid NOT NULL REFERENCES decisions(id) ON DELETE CASCADE, escrow_id uuid NOT NULL REFERENCES escrows(id) ON DELETE RESTRICT, instruction_id text NOT NULL UNIQUE, payload jsonb NOT NULL, payload_hex text NOT NULL, payload_sha256 text NOT NULL, destination_domain integer NOT NULL, status settlement_status NOT NULL DEFAULT 'draft', expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS hyperlane_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, instruction_id text NOT NULL REFERENCES settlement_instructions(instruction_id) ON DELETE CASCADE, message_id text UNIQUE, origin_domain integer NOT NULL, destination_domain integer NOT NULL, dispatch_tx_hash text, process_tx_hash text, delivery_status text NOT NULL DEFAULT 'pending', destination_execution_tx_hash text, destination_state_hash text, last_checked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS receipts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, case_id uuid NOT NULL REFERENCES cases(id) ON DELETE RESTRICT, decision_id uuid NOT NULL REFERENCES decisions(id) ON DELETE RESTRICT, instruction_id text NOT NULL REFERENCES settlement_instructions(instruction_id) ON DELETE RESTRICT, receipt_hash text NOT NULL UNIQUE, public_payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS x402_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, service_id uuid REFERENCES services(id) ON DELETE SET NULL, agent_id uuid REFERENCES agents(id) ON DELETE SET NULL, request_id text NOT NULL UNIQUE, network text NOT NULL, scheme text NOT NULL, payment_payload jsonb NOT NULL, payment_receipt jsonb, obligation jsonb NOT NULL, status text NOT NULL DEFAULT 'created', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS webhooks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, url text NOT NULL, events jsonb NOT NULL DEFAULT '[]'::jsonb, secret_ciphertext text NOT NULL, enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS webhook_deliveries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, webhook_id uuid NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE, event_type text NOT NULL, event_id text NOT NULL, payload jsonb NOT NULL, attempt integer NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'pending', next_attempt_at timestamptz, last_error text, delivered_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS integrations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, kind text NOT NULL, name text NOT NULL, config_ciphertext text NOT NULL, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS notification_preferences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE CASCADE, channels jsonb NOT NULL DEFAULT '{"email":true,"inApp":true}'::jsonb, events jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE CASCADE, event_type text NOT NULL, title text NOT NULL, body text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS billing_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL UNIQUE REFERENCES organizations(id) ON DELETE CASCADE, stripe_customer_id text UNIQUE, plan text NOT NULL DEFAULT 'starter', status text NOT NULL DEFAULT 'inactive', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS billing_subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, stripe_subscription_id text NOT NULL UNIQUE, stripe_price_id text NOT NULL, status text NOT NULL, current_period_end timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS usage_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, event_name text NOT NULL, quantity bigint NOT NULL, idempotency_key text NOT NULL UNIQUE, stripe_event_identifier text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tvg_ledger (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, agreement_id uuid REFERENCES agreements(id) ON DELETE SET NULL, case_id uuid REFERENCES cases(id) ON DELETE SET NULL, kind text NOT NULL, asset text NOT NULL, amount numeric(78,0) NOT NULL, route_key text, dedupe_key text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reputation_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, subject_type text NOT NULL, subject_id text NOT NULL, case_id uuid REFERENCES cases(id) ON DELETE SET NULL, score_delta integer NOT NULL, reason text NOT NULL, finalized boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, actor_type text NOT NULL, actor_id text NOT NULL, action text NOT NULL, resource_type text NOT NULL, resource_id text, ip text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
