// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;
import {Script,console2} from "forge-std/Script.sol";import {StudioDecisionGateway} from "../src/StudioDecisionGateway.sol";import {PraestEscrow} from "../src/PraestEscrow.sol";import {PraestSettlementReceiver} from "../src/PraestSettlementReceiver.sol";import {IMailbox} from "../src/interfaces/IHyperlane.sol";import {PraestTestSettlementToken} from "../src/PraestTestSettlementToken.sol";import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
contract DeployGateway is Script{function run()external{address mailbox=vm.envAddress("HYPERLANE_MAILBOX");uint256 pk=vm.envUint("EVM_DEPLOYER_PRIVATE_KEY_UINT");address admin=vm.addr(pk);vm.startBroadcast(pk);StudioDecisionGateway g=new StudioDecisionGateway(admin,mailbox);vm.stopBroadcast();console2.log("gateway",address(g));}}
contract DeployDestination is Script{function run()external{address mailbox=vm.envAddress("HYPERLANE_MAILBOX");uint32 local=uint32(vm.envUint("HYPERLANE_LOCAL_DOMAIN"));uint32 origin=uint32(vm.envUint("PRAEST_ORIGIN_DOMAIN"));bytes32 sender=vm.envBytes32("PRAEST_ORIGIN_SENDER");uint256 pk=vm.envUint("EVM_DEPLOYER_PRIVATE_KEY_UINT");address admin=vm.addr(pk);address ism=address(IMailbox(mailbox).defaultIsm());require(ism!=address(0),"default ISM unavailable");vm.startBroadcast(pk);PraestEscrow e=new PraestEscrow(admin);PraestSettlementReceiver r=new PraestSettlementReceiver(admin,mailbox,local,origin,sender,ism,e);e.setSettler(address(r),true);vm.stopBroadcast();console2.log("escrow",address(e));console2.log("receiver",address(r));console2.log("ism",ism);}}

/// @notice Redeploys only the receiver against an existing escrow, re-grants SETTLER_ROLE, and
/// authorises the bridge key for the same-chain direct path. Leaves funded escrow state intact.
contract UpgradeReceiver is Script{function run()external{address mailbox=vm.envAddress("HYPERLANE_MAILBOX");uint32 local=uint32(vm.envUint("HYPERLANE_LOCAL_DOMAIN"));uint32 origin=uint32(vm.envUint("PRAEST_ORIGIN_DOMAIN"));bytes32 sender=vm.envBytes32("PRAEST_ORIGIN_SENDER");address bridge=vm.envAddress("PRAEST_BRIDGE_ADDRESS");PraestEscrow e=PraestEscrow(vm.envAddress("PRAEST_ESCROW"));uint256 pk=vm.envUint("EVM_DEPLOYER_PRIVATE_KEY_UINT");address admin=vm.addr(pk);address ism=address(IMailbox(mailbox).defaultIsm());require(ism!=address(0),"default ISM unavailable");vm.startBroadcast(pk);PraestSettlementReceiver r=new PraestSettlementReceiver(admin,mailbox,local,origin,sender,ism,e);e.setSettler(address(r),true);r.grantRole(r.DIRECT_SETTLER_ROLE(),bridge);vm.stopBroadcast();console2.log("receiver",address(r));console2.log("ism",ism);console2.log("directSettler",bridge);}}

/// @notice Deploys the labelled test settlement asset and mints the deployer a working balance.
/// Only for testnet proofs - real settlement uses whatever ERC-20 the agreement names.
contract DeployTestToken is Script{function run()external{uint256 pk=vm.envUint("EVM_DEPLOYER_PRIVATE_KEY_UINT");address owner=vm.addr(pk);uint256 amount=vm.envOr("TEST_TOKEN_MINT",uint256(1_000_000e6));vm.startBroadcast(pk);PraestTestSettlementToken t=new PraestTestSettlementToken(owner);t.mint(owner,amount);vm.stopBroadcast();console2.log("testToken",address(t));console2.log("mintedTo",owner);console2.log("amount",amount);}}

/// @notice Funds one escrow so the settlement path can be exercised. Approves then funds, binding
/// the escrow policy (provider, customer, remedy cap) that every later decision must respect.
contract FundEscrow is Script{function run()external{uint256 pk=vm.envUint("EVM_DEPLOYER_PRIVATE_KEY_UINT");address payer=vm.addr(pk);PraestEscrow e=PraestEscrow(vm.envAddress("PRAEST_ESCROW"));address token=vm.envAddress("PRAEST_SETTLEMENT_TOKEN");bytes32 escrowId=vm.envBytes32("PRAEST_ESCROW_ID");bytes32 agreementId=vm.envBytes32("PRAEST_AGREEMENT_ID");address provider=vm.envAddress("PRAEST_PROVIDER");address customer=vm.envAddress("PRAEST_CUSTOMER");uint16 maxBps=uint16(vm.envUint("PRAEST_MAX_REMEDY_BPS"));uint256 amount=vm.envUint("PRAEST_ESCROW_AMOUNT");vm.startBroadcast(pk);IERC20(token).approve(address(e),amount);e.fund(escrowId,agreementId,token,provider,customer,maxBps,amount);vm.stopBroadcast();console2.log("funded escrow",address(e));console2.log("payer",payer);console2.log("amount",amount);}}
