import dns from "node:dns/promises";import https from "node:https";import tls from "node:tls";import net from "node:net";import {randomUUID,createHash} from "node:crypto";import {performance} from "node:perf_hooks";
const privateIp=(ip:string)=>/^(127\.|10\.|192\.168\.|169\.254\.|0\.|::1$|fc|fd)/i.test(ip)||(/^172\.(\d+)\./.test(ip)&&Number(ip.split('.')[1])>=16&&Number(ip.split('.')[1])<=31);
function getPath(obj:any,path:string){return path.split('.').filter(Boolean).reduce((a:any,x)=>a?.[x],obj)}
async function probeOne(t:any,step:any){
 const u=new URL(step.url||t.url);if(u.protocol!=="https:")throw new Error("HTTPS only");const rr=await dns.lookup(u.hostname,{all:true});if(!rr.length||rr.some(x=>privateIp(x.address)))throw new Error("unsafe target");const ip=rr[0]!.address;const started=performance.now();
 const dnsAt=performance.now();await dns.lookup(u.hostname);const dnsMs=performance.now()-dnsAt;
 const tcpAt=performance.now();await new Promise<void>((resolve,reject)=>{const s=net.connect({host:ip,port:Number(u.port||443)});s.once("connect",()=>{s.destroy();resolve()});s.once("error",reject);s.setTimeout(t.timeoutMs,()=>s.destroy(new Error("tcp timeout")))});const tcpMs=performance.now()-tcpAt;
 const tlsAt=performance.now();await new Promise<void>((resolve,reject)=>{const s=tls.connect({host:ip,port:Number(u.port||443),servername:u.hostname,rejectUnauthorized:true});s.once("secureConnect",()=>{s.destroy();resolve()});s.once("error",reject);s.setTimeout(t.timeoutMs,()=>s.destroy(new Error("tls timeout")))});const tlsMs=performance.now()-tlsAt;
 let statusCode=0,bytes=0,ttfbMs=0,responseHeaders:Record<string,string|string[]|undefined>={};const reqBody=step.body??t.assertions?.body;const headers={host:u.host,"user-agent":"PRAEST-Probe/1.0",...(t.authHeaders||{})};
 const body=await new Promise<string>((resolve,reject)=>{const request=https.request({hostname:ip,port:Number(u.port||443),path:u.pathname+u.search,method:step.method||t.method||"GET",headers,servername:u.hostname,rejectUnauthorized:true,timeout:t.timeoutMs},res=>{statusCode=res.statusCode||0;responseHeaders=res.headers as any;ttfbMs=performance.now()-started;const chunks:Buffer[]=[];res.on("data",c=>{bytes+=c.length;if(bytes<=512000)chunks.push(c)});res.on("end",()=>resolve(Buffer.concat(chunks).toString("utf8")))});request.on("error",reject);request.on("timeout",()=>request.destroy(new Error("http timeout")));if(reqBody)request.write(reqBody);request.end()});
 const totalMs=performance.now()-started,a={...(t.assertions||{}),...step};let ok=statusCode>=200&&statusCode<400;const expected=a.expectedStatus;if(expected!==undefined)ok=Array.isArray(expected)?expected.includes(statusCode):Number(expected)===statusCode;if(a.maxLatencyMs)ok=ok&&totalMs<=Number(a.maxLatencyMs);if(a.contentIncludes)ok=ok&&body.includes(String(a.contentIncludes));
 for(const [k,v] of Object.entries(a.headerEquals||{})){const actual=responseHeaders[String(k).toLowerCase()];ok=ok&&String(Array.isArray(actual)?actual.join(","):actual||"")===String(v)}
 let json:any;try{json=JSON.parse(body)}catch{};for(const [k,v] of Object.entries(a.jsonPath||{})){const actual=getPath(json,k);if(JSON.stringify(actual)!==JSON.stringify(v))ok=false}
 return {name:step.name||"primary",url:u.origin+u.pathname,statusCode,dnsMs,tcpMs,tlsMs,ttfbMs,totalMs,responseBytes:bytes,responseDigest:createHash("sha256").update(body).digest("hex"),ok};
}
async function probe(t:any,region:string){const steps=(t.assertions?.steps||[]).length?t.assertions.steps:[{name:"primary",url:t.url,method:t.method,body:t.assertions?.body,expectedStatus:t.assertions?.expectedStatus,maxLatencyMs:t.assertions?.maxLatencyMs,contentIncludes:t.assertions?.contentIncludes,headerEquals:t.assertions?.headerEquals,jsonPath:t.assertions?.jsonPath}];const results=[];for(const step of steps)results.push(await probeOne(t,step));const ok=results.every(x=>x.ok),first=results[0]!,total=results.reduce((n,x)=>n+x.totalMs,0);return {measurementId:randomUUID(),monitorId:t.id,organizationId:t.organizationId,serviceId:t.serviceId,region,workerVersion:process.env.AWS_LAMBDA_FUNCTION_VERSION||"local",collectorStatus:"OK",classification:ok?"SERVICE_OK":"SERVICE_FAILURE",statusCode:first.statusCode,dnsMs:first.dnsMs,tcpMs:first.tcpMs,tlsMs:first.tlsMs,ttfbMs:first.ttfbMs,totalMs:total,responseDigest:first.responseDigest,assertions:{steps:results},observedAt:new Date().toISOString(),summary:ok?"Assertions satisfied":"One or more synthetic steps/assertions failed"}}
export async function handler(event:any){const api=process.env.PRAEST_API_URL,token=process.env.PRAEST_INTERNAL_TOKEN,region=process.env.AWS_REGION||event.region;if(!api||!token||!region)throw new Error("PRAEST_API_URL, PRAEST_INTERNAL_TOKEN and region required");const headers={"content-type":"application/json","x-praest-internal-token":token};const targets=await fetch(`${api}/v1/internal/probes/targets?region=${encodeURIComponent(region)}`,{headers}).then(r=>{if(!r.ok)throw new Error(`targets ${r.status}`);return r.json()}) as any[];const minute=Math.floor(Date.now()/60000);const selected=targets.filter(t=>minute%Math.max(1,Math.ceil(Number(t.intervalSeconds||60)/60))===Math.abs(hash(t.id))%Math.max(1,Math.ceil(Number(t.intervalSeconds||60)/60)));for(const t of selected){let m:any;try{m=await probe(t,region)}catch(e:any){m={measurementId:randomUUID(),monitorId:t.id,organizationId:t.organizationId,serviceId:t.serviceId,region,workerVersion:process.env.AWS_LAMBDA_FUNCTION_VERSION||"local",collectorStatus:"COLLECTOR_ERROR",classification:"UNKNOWN",error:String(e.message||e),observedAt:new Date().toISOString()}}const res=await fetch(`${api}/v1/internal/probes/measurements`,{method:"POST",headers,body:JSON.stringify(m)});if(!res.ok)throw new Error(`measurement ingest ${res.status}`)}return {region,total:targets.length,ran:selected.length}}
function hash(s:string){let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return h}
