import {createDatabase,settlementInstructions,hyperlaneMessages,chainRoutes,decisions,escrows,receipts,cases} from "@praest/database";import {and,eq,inArray} from "drizzle-orm";import {createAccount,createClient} from "genlayer-js";import * as glChains from "genlayer-js/chains";import {TransactionHashVariant} from "genlayer-js/types";import {createPublicClient,createWalletClient,http,parseEventLogs,hexToBytes,bytesToHex,keccak256,toHex} from "viem";import {privateKeyToAccount} from "viem/accounts";import {gatewayAbi,mailboxAbi,receiverAbi} from "./abis.js";import {createHash} from "node:crypto";import {PublicKey} from "@solana/web3.js";
const {db,pool}=createDatabase();const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));

// The chain PRAEST dispatches from. GenLayer is the logical origin of every decision but is not
// itself a Hyperlane domain, so an EVM chain carries the message. Configurable because this moved
// once already (zkSync Sepolia -> Ethereum Sepolia) and will move again.
const sourceDomain=Number(process.env.PRAEST_HYPERLANE_ORIGIN_DOMAIN||11155111);

/**
 * Settlement transport, per destination route.
 *
 *  direct    - submit the instruction straight to the receiver via settleDirect(). No message, no
 *              validators, no relayer. The receiver still applies every instruction check; only
 *              the transport checks are replaced by DIRECT_SETTLER_ROLE. Trust is PRAEST's bridge
 *              key, bounded by the escrow's own allocation policy.
 *  hyperlane - dispatch through the Hyperlane Mailbox and let the destination ISM verify a
 *              validator quorum before the receiver ever sees it. Trust moves to Hyperlane's
 *              validator set, at the cost of depending on relayer liveness.
 *
 * The mode is explicit per route rather than inferred, so a misconfigured route fails loudly
 * instead of silently choosing a weaker path.
 */
type SettlementMode="direct"|"hyperlane";
function settlementMode(route:any):SettlementMode{const m=(route?.metadata as any)?.settlementMode;if(m==="direct"||m==="hyperlane")return m;return "direct"}

// Four states, tracked separately. "Dispatched" is not "delivered", and "delivered" is not
// "settled" - collapsing them hides exactly the failures worth seeing.
const DISPATCHED="dispatched",DELIVERED="delivered",PROCESSED="processed",SETTLED="settled";
function env(n:string){const v=process.env[n];if(!v)throw new Error(`${n} required`);return v}function account(){return privateKeyToAccount(env("BRIDGE_EVM_PRIVATE_KEY") as `0x${string}`)}function rpc(name:string){return env(name)}function toB32(address:string){if(address.startsWith("0x")){return (`0x${address.slice(2).padStart(64,'0')}`) as `0x${string}`;}const bs58=requireBs58(address);return bytesToHex(bs58) as `0x${string}`}function requireBs58(s:string){const alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(const c of s){const i=alphabet.indexOf(c);if(i<0)throw new Error('bad base58');n=n*58n+BigInt(i)}const out=[] as number[];while(n){out.unshift(Number(n%256n));n/=256n}for(const c of s){if(c==='1')out.unshift(0);else break}if(out.length!==32)throw new Error('expected 32-byte address');return new Uint8Array(out)}
function studio(){const pk=process.env.GENLAYER_STUDIONET_PRIVATE_KEY||process.env.GENLAYER_PRIVATE_KEY;if(!pk)throw new Error("GENLAYER_STUDIONET_PRIVATE_KEY required");const networkName=process.env.GENLAYER_NETWORK||"studioDevnet";const chain=(glChains as any)[networkName];if(!chain)throw new Error(`unknown GenLayer chain preset: ${networkName}`);return createClient({chain,account:createAccount(pk as `0x${string}`)})}
async function dispatchOne(x:any){const outbox=env("GENLAYER_DECISION_OUTBOX_ADDRESS");const gl:any=studio();const onchain:any=await gl.readContract({address:outbox,functionName:"get_instruction",args:[x.instructionId],transactionHashVariant:TransactionHashVariant.LATEST_FINAL});if(!onchain||String(onchain.instruction_id)!==x.instructionId||String(onchain.payload_hex).toLowerCase()!==String(x.payloadHex).toLowerCase()||String(onchain.decision_hash)!==String(x.payload?.decisionHash||''))throw new Error(`DecisionOutbox mismatch for ${x.instructionId}`);if(Number(onchain.destination_domain)!==x.destinationDomain)throw new Error('destination mismatch');if(Number(onchain.expires_at)*1000<Date.now())throw new Error('instruction expired');const [route]=await db.select().from(chainRoutes).where(eq(chainRoutes.domainId,x.destinationDomain)).limit(1);if(!route?.enabled||!route.receiver)throw new Error(`destination ${x.destinationDomain} not deploy-configured`);const mode=settlementMode(route);if(mode==="direct")return dispatchDirect(x,route);return dispatchHyperlane(x,route)}

/**
 * Same-chain path. Submits the instruction straight to the destination receiver - no Hyperlane
 * message, so nothing here depends on validator or relayer liveness.
 *
 * Idempotency has two layers: the receiver refuses a repeated instructionId on-chain, and we check
 * that before spending gas. A crash between the transaction landing and the database write is
 * therefore safe - the next cycle sees processedInstructions already true and reconciles instead
 * of resubmitting.
 */
async function dispatchDirect(x:any,route:any){const url=process.env[route.rpcEnv];if(!url)throw new Error(`${route.rpcEnv} required for ${route.key}`);const pub=createPublicClient({transport:http(url)});const receiver=route.receiver as `0x${string}`;const instructionId=x.instructionId as `0x${string}`;
 const already=await pub.readContract({address:receiver,abi:receiverAbi,functionName:"processedInstructions",args:[instructionId]}).catch(()=>false);
 if(already){console.log('already processed on-chain, recording instead of resubmitting',x.instructionId);await recordDispatch(x,null,undefined,PROCESSED);return}
 const wallet=createWalletClient({account:account(),transport:http(url)});
 const hash=await wallet.writeContract({address:receiver,abi:receiverAbi,functionName:"settleDirect",args:[x.payloadHex as `0x${string}`],chain:null});
 const receipt=await pub.waitForTransactionReceipt({hash});
 if(receipt.status!=="success")throw new Error(`settleDirect reverted: ${hash}`);
 await recordDispatch(x,null,hash,PROCESSED);
 console.log('settled direct',x.instructionId,hash)}

/** Cross-chain path. Dispatches through the Hyperlane Mailbox on the configured origin chain. */
async function dispatchHyperlane(x:any,route:any){const [origin]=await db.select().from(chainRoutes).where(eq(chainRoutes.domainId,sourceDomain)).limit(1);const originRpc=origin?.rpcEnv?process.env[origin.rpcEnv]:undefined;if(!originRpc)throw new Error(`origin domain ${sourceDomain} has no configured RPC`);const wallet=createWalletClient({account:account(),transport:http(originRpc)});const pub=createPublicClient({transport:http(originRpc)});const gateway=env("PRAEST_STUDIO_GATEWAY_ADDRESS") as `0x${string}`;const recipient=toB32(route.receiver);const payload=x.payloadHex as `0x${string}`;const fee=await pub.readContract({address:gateway,abi:gatewayAbi,functionName:"quote",args:[x.destinationDomain,recipient,payload]});const hash=await wallet.writeContract({address:gateway,abi:gatewayAbi,functionName:"dispatchInstruction",args:[x.instructionId as `0x${string}`,x.destinationDomain,recipient,payload],value:fee,chain:null});const receipt=await pub.waitForTransactionReceipt({hash});const logs=parseEventLogs({abi:gatewayAbi,logs:receipt.logs,eventName:"InstructionDispatched"});const messageId=(logs[0] as any)?.args?.messageId;if(!messageId)throw new Error('dispatch event missing');await recordDispatch(x,messageId,hash,DISPATCHED);console.log('dispatched',x.instructionId,messageId)}

async function recordDispatch(x:any,messageId:string|null,dispatchTxHash:string|undefined,status:string){await db.insert(hyperlaneMessages).values({organizationId:x.organizationId,instructionId:x.instructionId,messageId,originDomain:sourceDomain,destinationDomain:x.destinationDomain,dispatchTxHash,deliveryStatus:status}).onConflictDoNothing();await db.update(settlementInstructions).set({status:"dispatched",updatedAt:new Date()}).where(eq(settlementInstructions.id,x.id))}
async function reconcileEvm(m:any,route:any,x:any){const url=process.env[route.rpcEnv];if(!url||!route.receiver)return;const pub=createPublicClient({transport:http(url)});const instructionId=x.instructionId as `0x${string}`;
 // Transport check, cross-chain only. A direct settlement never produced a Hyperlane message, so
 // there is nothing for the Mailbox to have delivered - go straight to the application check.
 if(m.messageId){const delivered=await pub.readContract({address:route.mailbox as `0x${string}`,abi:mailboxAbi,functionName:"delivered",args:[m.messageId as `0x${string}`]}).catch(()=>false);if(!delivered)return;if(m.deliveryStatus===DISPATCHED)await db.update(hyperlaneMessages).set({deliveryStatus:DELIVERED,lastCheckedAt:new Date(),updatedAt:new Date()}).where(eq(hyperlaneMessages.id,m.id));}
 // Application check. Hyperlane delivering a message is not PRAEST accepting it: the receiver
 // re-validates the instruction and can still refuse, so "delivered" must never be read as "settled".
 const processed=await pub.readContract({address:route.receiver as `0x${string}`,abi:receiverAbi,functionName:"processedInstructions",args:[instructionId]}).catch(()=>false);if(!processed){await db.update(hyperlaneMessages).set({deliveryStatus:m.messageId?DELIVERED:DISPATCHED,lastCheckedAt:new Date(),updatedAt:new Date()}).where(eq(hyperlaneMessages.id,m.id));return}
 if(m.deliveryStatus!==PROCESSED&&m.deliveryStatus!==SETTLED)await db.update(hyperlaneMessages).set({deliveryStatus:PROCESSED,lastCheckedAt:new Date(),updatedAt:new Date()}).where(eq(hyperlaneMessages.id,m.id));const bound=await pub.readContract({address:route.receiver as `0x${string}`,abi:receiverAbi,functionName:"instructionDecision",args:[instructionId]});const expected=String(x.payload?.decisionHash||'').toLowerCase();if(String(bound).toLowerCase()!==expected)throw new Error('destination decision binding mismatch');const latest=await pub.getBlockNumber();const from=latest>20000n?latest-20000n:0n;let txHash:string|undefined;try{const logs=await pub.getLogs({address:route.receiver as `0x${string}`,event:{type:'event',name:'SettlementExecuted',inputs:[{indexed:true,name:'instructionId',type:'bytes32'},{indexed:true,name:'decisionHash',type:'bytes32'},{indexed:false,name:'escrowId',type:'bytes32'},{indexed:false,name:'total',type:'uint256'}]},args:{instructionId},fromBlock:from,toBlock:'latest'});txHash=logs.at(-1)?.transactionHash}catch{}await settle(m,x,txHash||undefined,`evm:${route.key}:${bound}`)}
async function reconcileSolana(m:any,route:any,x:any){const url=process.env[route.rpcEnv];if(!url||!route.receiver)return;const [esc]=await db.select().from(escrows).where(eq(escrows.id,x.escrowId)).limit(1);if(!esc?.onchainEscrowId)return;const program=new PublicKey(route.receiver);const seed=Buffer.from(String(esc.onchainEscrowId).replace(/^0x/,""),"hex");if(seed.length!==32)throw new Error("invalid Solana escrow id");const [escrowPda]=PublicKey.findProgramAddressSync([Buffer.from("praest-escrow"),seed],program);const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:1,method:"getAccountInfo",params:[escrowPda.toBase58(),{encoding:"base64",commitment:"confirmed"}]})});if(!r.ok)throw new Error(`Solana RPC ${r.status}`);const j:any=await r.json();const b64=j?.result?.value?.data?.[0];if(!b64)return;const data=Buffer.from(b64,"base64");const needle=Buffer.from(String(x.instructionId).replace(/^0x/,""),"hex");if(needle.length!==32||!data.includes(needle))return;const stateHash="0x"+createHash("sha256").update(data).digest("hex");await settle(m,x,undefined,stateHash)}
async function settle(m:any,x:any,txHash?:string,stateHash?:string){const [d]=await db.select().from(decisions).where(eq(decisions.id,x.decisionId)).limit(1);if(!d)return;const [c]=await db.select().from(cases).where(eq(cases.id,d.caseId)).limit(1);if(!c)return;const publicPayload={caseId:c.id,decisionId:d.id,decisionHash:d.decisionHash,instructionId:x.instructionId,destinationDomain:x.destinationDomain,dispatchTxHash:m.dispatchTxHash,hyperlaneMessageId:m.messageId,destinationExecutionTxHash:txHash||null,destinationStateHash:stateHash||null,settledAt:new Date().toISOString()};const receiptHash='0x'+createHash('sha256').update(JSON.stringify(publicPayload,Object.keys(publicPayload).sort())).digest('hex');await db.transaction(async(tx:any)=>{await tx.update(hyperlaneMessages).set({deliveryStatus:SETTLED,destinationExecutionTxHash:txHash,destinationStateHash:stateHash,lastCheckedAt:new Date(),updatedAt:new Date()}).where(eq(hyperlaneMessages.id,m.id));await tx.update(settlementInstructions).set({status:"settled",updatedAt:new Date()}).where(eq(settlementInstructions.id,x.id));await tx.insert(receipts).values({organizationId:x.organizationId,caseId:c.id,decisionId:d.id,instructionId:x.instructionId,receiptHash,publicPayload}).onConflictDoNothing();await tx.update(cases).set({status:"settled",updatedAt:new Date()}).where(eq(cases.id,c.id))});console.log('settled',x.instructionId)}
async function cycle(){const pending=await db.select().from(settlementInstructions).where(eq(settlementInstructions.status,"authorized"));for(const x of pending)try{await dispatchOne(x)}catch(e){console.error('dispatch',x.instructionId,e)}const msgs=await db.select().from(hyperlaneMessages).where(inArray(hyperlaneMessages.deliveryStatus,[DISPATCHED,DELIVERED,PROCESSED]));for(const m of msgs){const [x]=await db.select().from(settlementInstructions).where(eq(settlementInstructions.instructionId,m.instructionId)).limit(1);const [r]=await db.select().from(chainRoutes).where(eq(chainRoutes.domainId,m.destinationDomain)).limit(1);if(!x||!r)continue;try{if(r.protocol==='ethereum')await reconcileEvm(m,r,x);else await reconcileSolana(m,r,x)}catch(e){console.error('reconcile',x.instructionId,e)}}}
async function main(){console.log('PRAEST bridge/indexer starting');while(true){await cycle().catch(console.error);await sleep(Number(process.env.BRIDGE_POLL_MS||10000))}}main().finally(()=>pool.end()).catch(e=>{console.error(e);process.exit(1)})
