import {Body,Controller,ForbiddenException,Headers,Inject,Post,RawBodyRequest,Req} from "@nestjs/common";import type {FastifyRequest} from "fastify";import Stripe from "stripe";import {DB} from "./database.module.js";import {billingAccounts,billingSubscriptions,usageEvents} from "@praest/database";import {eq} from "drizzle-orm";import {hasPermission} from "./request-context.js";import {Public} from "./public.decorator.js";
export class BillingService{private stripe(){if(!process.env.STRIPE_SECRET_KEY)throw new Error("STRIPE_SECRET_KEY required");return new Stripe(process.env.STRIPE_SECRET_KEY)}constructor(@Inject(DB)private db:any){}async customer(org:string,email?:string){let [b]=await this.db.select().from(billingAccounts).where(eq(billingAccounts.organizationId,org)).limit(1);if(!b){const c=await this.stripe().customers.create({email,metadata:{praestOrganizationId:org}});[b]=await this.db.insert(billingAccounts).values({organizationId:org,stripeCustomerId:c.id}).returning()}return b}async checkout(org:string,email:string,plan:"starter"|"pro"){const b=await this.customer(org,email);const price=plan==="pro"?process.env.STRIPE_PRICE_PRO:process.env.STRIPE_PRICE_STARTER;if(!price)throw new Error("Stripe price not configured");return this.stripe().checkout.sessions.create({mode:"subscription",customer:b.stripeCustomerId!,line_items:[{price,quantity:1}],success_url:`${process.env.PRAEST_APP_URL}/app/billing?checkout=success`,cancel_url:`${process.env.PRAEST_APP_URL}/app/billing?checkout=cancelled`,metadata:{praestOrganizationId:org,plan}})}async portal(org:string){const b=await this.customer(org);return this.stripe().billingPortal.sessions.create({customer:b.stripeCustomerId!,return_url:`${process.env.PRAEST_APP_URL}/app/billing`})}async usage(org:string,eventName:string,quantity:bigint,key:string){const [row]=await this.db.insert(usageEvents).values({organizationId:org,eventName,quantity,idempotencyKey:key}).onConflictDoNothing().returning();if(!row)return {deduplicated:true};const b=await this.customer(org);const ev=await (this.stripe().billing.meterEvents as any).create({event_name:process.env.STRIPE_METER_EVENT_NAME||eventName,payload:{stripe_customer_id:b.stripeCustomerId,value:quantity.toString()},identifier:key,timestamp:Math.floor(Date.now()/1000)});await this.db.update(usageEvents).set({stripeEventIdentifier:ev.identifier||key}).where(eq(usageEvents.id,row.id));return row}async webhook(raw:Buffer,sig:string){const secret=process.env.STRIPE_WEBHOOK_SECRET;if(!secret)throw new Error("STRIPE_WEBHOOK_SECRET required");const e=this.stripe().webhooks.constructEvent(raw,sig,secret);if(e.type.startsWith("customer.subscription.")){const sub=e.data.object as Stripe.Subscription;const customer=String(sub.customer);const [b]=await this.db.select().from(billingAccounts).where(eq(billingAccounts.stripeCustomerId,customer)).limit(1);if(b){
  // Stripe API 2025+ moved current_period_end from the subscription itself to each subscription item.
  const item=sub.items.data[0];const priceId=item?.price.id||"unknown";const periodEndSec=(item as any)?.current_period_end;const currentPeriodEnd=periodEndSec?new Date(periodEndSec*1000):null;
  await this.db.insert(billingSubscriptions).values({organizationId:b.organizationId,stripeSubscriptionId:sub.id,stripePriceId:priceId,status:sub.status,currentPeriodEnd}).onConflictDoUpdate({target:billingSubscriptions.stripeSubscriptionId,set:{status:sub.status,currentPeriodEnd,stripePriceId:priceId}});
  const plan=priceId===process.env.STRIPE_PRICE_PRO?"pro":priceId===process.env.STRIPE_PRICE_STARTER?"starter":b.plan;
  const accountStatus=(sub.status==="active"||sub.status==="trialing")?"active":sub.status;
  await this.db.update(billingAccounts).set({plan,status:accountStatus,updatedAt:new Date()}).where(eq(billingAccounts.id,b.id));
}}return {received:true,type:e.type}}}
@Controller("v1/billing") export class BillingController{constructor(private svc:BillingService){}@Post("checkout") checkout(@Req()r:any,@Body()b:any){if(!hasPermission(r.praestActor,"billing:write"))throw new ForbiddenException();return this.svc.checkout(r.praestActor.organizationId,r.praestActor.email,b.plan)}@Post("portal") portal(@Req()r:any){if(!hasPermission(r.praestActor,"billing:read"))throw new ForbiddenException();return this.svc.portal(r.praestActor.organizationId)}@Post("usage") usage(@Req()r:any,@Body()b:any){if(!hasPermission(r.praestActor,"billing:write"))throw new ForbiddenException();return this.svc.usage(r.praestActor.organizationId,b.eventName,BigInt(b.quantity),b.idempotencyKey)}@Public()@Post("webhook") webhook(@Req()req:RawBodyRequest<FastifyRequest>,@Headers("stripe-signature")sig:string){if(!req.rawBody)throw new Error("raw body unavailable");return this.svc.webhook(req.rawBody,sig)}}
