import {Body,Controller,Inject,Post,Req,UnauthorizedException} from "@nestjs/common";import {DB} from "./database.module.js";import {organizations,users,memberships,wallets} from "@praest/database";import {eq} from "drizzle-orm";import {PrivyClient} from "@privy-io/node";
@Controller("v1/bootstrap") export class BootstrapController{constructor(@Inject(DB)private db:any){} @Post() async run(@Req()req:any,@Body()body:any){const a=req.praestActor;if(!a||a.type!=="user")throw new UnauthorizedException();
 // The organization MUST come from the verified WorkOS JWT's org_id claim (set in AuthGuard) -
 // never from the request body. Trusting a client-supplied org id here would let any authenticated
 // caller become "owner" (permissions:["*"]) of an arbitrary existing organization by guessing or
 // knowing its id.
 const workosOrg=a.workosOrganizationId;if(!workosOrg)throw new UnauthorizedException("Your WorkOS session is not scoped to an organization yet - complete WorkOS organization membership/invitation before calling bootstrap");let [u]=await this.db.select().from(users).where(eq(users.workosUserId,a.id)).limit(1);if(!u){[u]=await this.db.insert(users).values({workosUserId:a.id,email:a.email||body.email||"unknown@example.invalid",displayName:body.displayName||null}).returning();}let [o]=await this.db.select().from(organizations).where(eq(organizations.workosOrganizationId,workosOrg)).limit(1);if(!o){[o]=await this.db.insert(organizations).values({workosOrganizationId:workosOrg,name:body.organizationName||"PRAEST Organisation",slug:(body.slug||`org-${crypto.randomUUID().slice(0,8)}`).toLowerCase()}).returning();}await this.db.insert(memberships).values({organizationId:o.id,userId:u.id,role:"owner",permissions:["*"]}).onConflictDoNothing();
 let privyUserId=u.privyUserId;const createdWallets:any[]=[];if(process.env.PRIVY_APP_ID&&process.env.PRIVY_APP_SECRET){const privy=new PrivyClient({appId:process.env.PRIVY_APP_ID,appSecret:process.env.PRIVY_APP_SECRET});let pu:any;try{pu=await (privy as any).users().getByCustomAuthID(a.id)}catch{pu=await (privy as any).users().create({linked_accounts:[{type:"custom_auth",custom_user_id:a.id},{type:"email",address:u.email}]})}privyUserId=pu.id;await this.db.update(users).set({privyUserId}).where(eq(users.id,u.id));for(const chain_type of ["ethereum","solana"]){let wallet=(pu.linked_accounts||[]).find((x:any)=>x.chain_type===chain_type);if(!wallet)wallet=await (privy as any).wallets().create({chain_type,owner:{user_id:pu.id}});await this.db.insert(wallets).values({organizationId:o.id,userId:u.id,ownerType:"user",ownerId:u.id,chainFamily:chain_type,address:wallet.address,provider:"privy",purpose:"embedded",verifiedAt:new Date()}).onConflictDoNothing();createdWallets.push({chainType:chain_type,address:wallet.address});}}
 return {user:{id:u.id,email:u.email,privyUserId},organization:o,wallets:createdWallets};}}
