import {Body,Controller,ForbiddenException,Inject,Post,Req} from "@nestjs/common";import {DB} from "./database.module.js";import {evidence,evidenceBundles,evidenceBundleItems,agreements} from "@praest/database";import {evidenceCreateSchema} from "@praest/schemas";import {hasPermission} from "./request-context.js";import {sha256,canonicalJson} from "./crypto.js";import {S3Client,PutObjectCommand} from "@aws-sdk/client-s3";import {and,eq} from "drizzle-orm";import {StudioNetAdapter} from "./genlayer.js";
export class EvidenceService{constructor(@Inject(DB)private db:any){} private s3(){return new S3Client({region:process.env.R2_REGION||"auto",endpoint:process.env.R2_ENDPOINT,credentials:process.env.R2_ACCESS_KEY_ID?{accessKeyId:process.env.R2_ACCESS_KEY_ID,secretAccessKey:process.env.R2_SECRET_ACCESS_KEY!}:undefined})} async create(org:string,input:any){const v=evidenceCreateSchema.parse(input);const [a]=await this.db.select().from(agreements).where(and(eq(agreements.id,v.agreementId),eq(agreements.organizationId,org))).limit(1);if(!a)throw new Error("agreement not found");const bytes=Buffer.from(v.body||canonicalJson(v.metadata));const hash=sha256(bytes);let objectKey:string|undefined;if(process.env.R2_ENDPOINT){objectKey=`evidence/${org}/${crypto.randomUUID()}`;await this.s3().send(new PutObjectCommand({Bucket:process.env.R2_BUCKET,Key:objectKey,Body:bytes,ContentType:v.body?"text/plain":"application/json",Metadata:{sha256:hash.slice(2)}}));}const [row]=await this.db.insert(evidence).values({organizationId:org,agreementId:v.agreementId,caseId:v.caseId,kind:v.kind,source:v.source,provenance:{collector:"praest",source:v.source,url:v.url||null,metadata:v.metadata},objectKey,sha256:hash,contentType:v.body?"text/plain":"application/json",sizeBytes:BigInt(bytes.length),observedAt:new Date()}).returning();return row} async lockBundle(org:string,agreementId:string,evidenceIds:string[]){const rows=await this.db.select().from(evidence).where(and(eq(evidence.organizationId,org),eq(evidence.agreementId,agreementId)));const selected=rows.filter((x:any)=>evidenceIds.includes(x.id));if(selected.length!==evidenceIds.length)throw new Error("invalid evidence set");const manifest={agreementId,items:selected.map((x:any)=>({id:x.id,sha256:x.sha256,source:x.source,kind:x.kind,url:x.provenance?.url||null,observedAt:x.observedAt||null,verificationStatus:x.verificationStatus})).sort((a:any,b:any)=>a.id.localeCompare(b.id))};const manifestHash=sha256(canonicalJson(manifest));const [bundle]=await this.db.insert(evidenceBundles).values({organizationId:org,agreementId,manifest,manifestHash,lockedAt:new Date()}).returning();for(let i=0;i<selected.length;i++)await this.db.insert(evidenceBundleItems).values({bundleId:bundle.id,evidenceId:selected[i].id,ordinal:i});
  // Get an independent GenLayer judgment (sufficiency/conflicts) on this locked bundle - validators
  // re-derive it themselves rather than trusting the leader's read of the manifest (see
  // EvidenceAssessor.assess's validator_fn). Queryable later via get_assessment(bundle.id).
  const assessor=process.env.GENLAYER_EVIDENCE_ASSESSOR_ADDRESS;
  if(!assessor)throw new Error("GENLAYER_EVIDENCE_ASSESSOR_ADDRESS required to lock an evidence bundle");
  await new StudioNetAdapter().write(assessor,"assess",[bundle.id,canonicalJson(manifest)]);
  return bundle}}
@Controller("v1/evidence") export class EvidenceController{constructor(private svc:EvidenceService){}@Post() create(@Req()req:any,@Body()b:any){if(!hasPermission(req.praestActor,"evidence:write"))throw new ForbiddenException();return this.svc.create(req.praestActor.organizationId,b)}@Post("bundles/lock") lock(@Req()req:any,@Body()b:any){if(!hasPermission(req.praestActor,"evidence:write"))throw new ForbiddenException();return this.svc.lockBundle(req.praestActor.organizationId,b.agreementId,b.evidenceIds)}}
