"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {api,resourceFromPath} from "@/lib/api";import {nav} from "@/lib/nav";import EscrowFundingAction from "@/components/EscrowFundingAction";
type Props={path:string};
const human=(s:string)=>s.replace(/[-_]/g," ").replace(/\b\w/g,c=>c.toUpperCase());
function section(path:string){if(path.startsWith('/control'))return 'control';if(path.startsWith('/developer'))return 'developer';if(path.startsWith('/explorer'))return 'explorer';return 'product'}
const endpointFor=(path:string)=>{if(path.includes('/api-keys'))return 'api-keys';if(path.includes('/webhooks'))return 'webhooks';if(path.includes('/routes'))return 'routes';return resourceFromPath(path)};
const resourceKey=(endpoint:string)=>({"agent-tasks":"agentTasks","agent-execution-receipts":"agentExecutionReceipts","agreement-versions":"agreementVersions","agreement-parties":"agreementParties","evidence-bundles":"evidenceBundles","tls-proofs":"tlsProofs","settlement-instructions":"settlementInstructions","hyperlane-messages":"hyperlaneMessages","x402-requests":"x402Requests","usage-events":"usageEvents","tvg-ledger":"tvgLedger","reputation-events":"reputationEvents","audit-logs":"auditLogs"} as Record<string,string>)[endpoint]||endpoint;
export default function Console({path}:Props){const sec=section(path) as keyof typeof nav;const bits=path.split('/').filter(Boolean);const title=human(bits.at(-1)?.startsWith('[')?bits.at(-2)||'PRAEST':bits.at(-1)||'PRAEST');const endpoint=endpointFor(path);const [rows,setRows]=useState<any[]>([]);const [err,setErr]=useState('');const [loading,setLoading]=useState(false);const id=bits.find(x=>/^[0-9a-f]{8}-/.test(x));
 useEffect(()=>{if(!endpoint||['dashboard','analytics','billing','mcp','openapi','playground','sdks','overview','genlayer','workflows','security','audit','monitoring','chains','hyperlane'].includes(endpoint))return;setLoading(true);api<any>(`${endpoint==='routes'||endpoint==='api-keys'?endpoint:`resources/${resourceKey(endpoint)}`}${id?`/${id}`:''}`).then(v=>setRows(Array.isArray(v)?v:[v])).catch(e=>setErr(e.message)).finally(()=>setLoading(false))},[endpoint,id]);
 const metrics=useMemo(()=>[['Surface',human(sec)],['Resource',human(endpoint||title)],['State',loading?'Loading':err?'Attention':'Ready'],['Mode',path.startsWith('/explorer')?'Verification':'Operational']], [sec,endpoint,title,loading,err,path]);
 return <div className="shell"><aside className="side"><div className="brand">PRAEST</div>{Object.entries(nav).map(([group,items])=><div key={group}><div className="nav-group">{group}</div>{items.map(([l,h])=><Link key={h} className="nav-item" href={h}>{l}</Link>)}</div>)}</aside><div className="main"><header className="top"><span className="eyebrow">{sec} plane</span><span className="pill">StudioNet</span></header><main className="content"><div className="eyebrow">{path}</div><h1 className="h1">{title}</h1><p className="sub">This surface is part of PRAEST's unified accountability lifecycle. Data is organisation-scoped and actions flow through the same API, evidence, adjudication and settlement state machines used by agents and SDK clients.</p><div className="grid">{metrics.map(([l,v])=><div className="card" key={l}><div className="metric">{v}</div><div className="label">{l}</div></div>)}</div>{err&&<div className="error">{err}</div>}<ActionPanel path={path} endpoint={endpoint}/>{path.startsWith("/app/escrows/")&&id&&<EscrowFundingAction escrowId={id}/>} {rows.length>0&&<DataTable rows={rows}/>}<ContextPanel path={path}/></main></div></div>}
function DataTable({rows}:{rows:any[]}){const cols=Object.keys(rows[0]||{}).filter(k=>!['payload','metadata','terms','manifest','rawDecision','ciphertext','configCiphertext'].includes(k)).slice(0,7);return <div style={{overflowX:'auto',marginTop:18}}><table className="table"><thead><tr>{cols.map(c=><th key={c}>{human(c)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{typeof r[c]==='object'?JSON.stringify(r[c]).slice(0,100):String(r[c]??'—')}</td>)}</tr>)}</tbody></table></div>}
function DirectAction({title,endpoint,body={}}:{title:string,endpoint:string,body?:any}){const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);return <div className="card" style={{marginTop:18}}><button className="btn primary" disabled={busy} onClick={async()=>{setBusy(true);setMsg('');try{const out=await api(endpoint,{method:'POST',body:JSON.stringify(body)});setMsg(`Success ${out?.id||out?.instruction?.instructionId||''}`.trim())}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}}>{busy?'Working…':title}</button>{msg&&<p className="muted">{msg}</p>}</div>}
function EndpointForm({title,endpoint,fields}:{title:string,endpoint:string,fields:string[][]}){const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);return <div className="card" style={{marginTop:18}}><h3>{title}</h3><form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);setMsg('');const raw:any=Object.fromEntries(new FormData(e.currentTarget).entries());for(const k of ['evidenceIds','events','permissions'])if(typeof raw[k]==='string')raw[k]=raw[k].split(',').map((x:string)=>x.trim()).filter(Boolean);for(const k of ['metadata','terms','paymentPayload','paymentRequirements','obligation'])if(typeof raw[k]==='string'&&raw[k])try{raw[k]=JSON.parse(raw[k])}catch{};try{const out=await api(endpoint,{method:'POST',body:JSON.stringify(raw)});setMsg(`Success ${out?.id||out?.instructionId||''}`.trim())}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}}>{fields.map(([n,l])=><div className="field" key={n}><label>{l}</label>{['claim','body','metadata','terms','paymentPayload','paymentRequirements','obligation'].includes(n)?<textarea name={n}/>:<input name={n}/>}</div>)}<button className="btn primary" disabled={busy}>{busy?'Working…':'Submit'}</button>{msg&&<p className="muted">{msg}</p>}</form></div>}
function ActionPanel({path,endpoint}:{path:string,endpoint?:string}){const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const dynId=path.split('/').find(x=>/^[0-9a-f]{8}-/.test(x));async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg('');const fd=new FormData(e.currentTarget);const raw=Object.fromEntries(fd.entries());let body:any={...raw};for(const k of ['terms','metadata','assertions','obligation','capabilities','authorityPolicy','paymentPayload','paymentRequirements'])if(typeof body[k]==='string'&&body[k])try{body[k]=JSON.parse(body[k])}catch{};try{let ep=endpoint||'';if(path.includes('/disputes/new'))ep='resolutions';else if(ep==='agreements'||path==='/app/events/new')ep='agreements';else if(ep==='monitors')ep='monitors';else if(ep==='escrows')ep='escrows';else if(ep==='api-keys')ep='api-keys';else if(ep==='webhooks')ep='webhooks';else ep=`resources/${resourceKey(ep)}`;const out=await api(ep,{method:'POST',body:JSON.stringify(body)});setMsg(`Created ${out.id||out.instructionId||'successfully'}`)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 if(path.startsWith('/app/cases/')&&dynId)return <DirectAction title="Submit to GenLayer" endpoint={`cases/${dynId}/adjudicate`}/>;
 if(path.startsWith('/app/adjudications/')&&dynId)return <><EndpointForm title="Appeal adjudication" endpoint={`adjudications/${dynId}/appeal`} fields={[["reason","Appeal reason"],["value","Optional GenLayer appeal value"]]}/><DirectAction title="Finalize and authorize settlement" endpoint={`adjudications/${dynId}/finalize`}/></>;
 if(path.startsWith('/app/agreements/')&&dynId&&!path.includes('/evidence')&&!path.includes('/settlement'))return <><EndpointForm title="Accept agreement version" endpoint={`agreements/${dynId}/accept`} fields={[["partyType","Party type"],["partyId","Party ID"],["role","Role (customer/provider/agent)"],["settlementAddress","Settlement address"],["version","Version"],["signature","Optional signature"]]}/><DirectAction title="Activate agreement" endpoint={`agreements/${dynId}/activate`}/></>;
 if(path==='/app/evidence')return <><EndpointForm title="Add evidence" endpoint="evidence" fields={[["agreementId","Agreement ID"],["caseId","Optional case ID"],["kind","Evidence kind"],["source","Source/provenance"],["url","Public HTTPS source URL"],["body","Evidence body"],["metadata","Metadata JSON"]]}/><EndpointForm title="Lock evidence bundle" endpoint="evidence/bundles/lock" fields={[["agreementId","Agreement ID"],["evidenceIds","Evidence IDs, comma-separated"]]}/></>;
 if(path==='/app/escrows')return <EndpointForm title="Create settlement escrow" endpoint="escrows" fields={[["agreementId","Agreement ID"],["routeKey","Route key"],["asset","Token/mint address"],["assetDecimals","Asset decimals"],["payerAddress","Payer address"],["providerAddress","Provider address"],["customerAddress","Customer address"],["amount","Amount in atomic units"],["maxCustomerRemedyBps","Customer remedy cap bps"]]}/>;
 if(path.startsWith('/app/services/')&&dynId)return <EndpointForm title="Add private service credential" endpoint={`services/${dynId}/credentials`} fields={[["name","Credential name"],["kind","Kind"],["secret","Secret or JSON string"]]}/>;
 if(path==='/app/x402/requests')return <EndpointForm title="Verify / settle x402 payment" endpoint="x402/verify-settle" fields={[["requestId","Optional request ID"],["serviceId","Service ID"],["agentId","Agent ID"],["paymentPayload","Payment payload JSON"],["paymentRequirements","Payment requirements JSON"],["obligation","Obligation JSON"]]}/>;
 if(path==='/app/x402/assurance')return <EndpointForm title="Open x402 assurance case" endpoint="x402/assurance" fields={[["requestId","x402 request ID"],["agreementId","Agreement ID"],["claim","Failure claim"]]}/>;
 if(path==='/developer/resolution')return <EndpointForm title="Create resolution case through PRAEST" endpoint="resolutions" fields={[["agreementId","Agreement ID"],["caseType","Case type"],["claim","Claim"],["requestedOutcome","Requested outcome"],["evidenceBundleId","Evidence bundle ID"]]}/>;
 if(path==='/app/services/new')return <Form title="Register service" onSubmit={submit} fields={[['name','Service name'],['kind','Kind'],['baseUrl','Base URL'],['description','Description']]}/>;
 if(path==='/app/agreements/new')return <Form title="Create agreement" onSubmit={submit} fields={[['name','Agreement name'],['kind','Kind'],['serviceId','Service ID'],['settlementRouteKey','Settlement route'],['settlementAsset','Asset'],['governedValue','Governed value (atomic units)'],['terms','Terms JSON']]}/>;
 if(path==='/app/monitors/new')return <Form title="Create monitor" onSubmit={submit} fields={[['serviceId','Service ID'],['name','Monitor name'],['url','HTTPS endpoint'],['method','Method'],['intervalSeconds','Interval seconds'],['timeoutMs','Timeout ms'],['assertions','Assertions JSON']]}/>;
 if(path==='/app/agents/new')return <Form title="Register agent" onSubmit={submit} fields={[['name','Agent name'],['description','Description'],['capabilities','Capabilities']]}/>;
 if(path==='/app/disputes/new')return <Form title="Open resolution case" onSubmit={submit} fields={[['agreementId','Agreement ID'],['caseType','Case type'],['claim','Claim'],['requestedOutcome','Requested outcome'],['evidenceBundleId','Evidence bundle ID']]}/>;
 if(path==='/app/events/new')return <Form title="Create event resolution agreement" onSubmit={submit} fields={[['name','Event'],['kind','Kind'],['settlementRouteKey','Settlement route'],['terms','Resolution terms JSON']]}/>;
 if(path==='/developer/api-keys')return <Form title="Create API key" onSubmit={submit} fields={[['name','Key name'],['permissions','Permissions, comma-separated']]}/>;
 if(path==='/developer/webhooks')return <Form title="Create webhook" onSubmit={submit} fields={[['url','HTTPS URL'],['events','Events'],['secret','Signing secret']]}/>;
 return null}
function Form({title,onSubmit,fields}:{title:string,onSubmit:any,fields:string[][]}){return <div className="card" style={{marginTop:18}}><h3>{title}</h3><form className="form" onSubmit={onSubmit}>{fields.map(([n,l])=><div className="field" key={n}><label>{l}</label>{['description','claim','terms','assertions'].includes(n)?<textarea name={n}/>:<input name={n} required={!['description','evidenceBundleId'].includes(n)}/>}</div>)}<button className="btn primary">Submit</button></form></div>}
function ContextPanel({path}:{path:string}){if(path.includes('hyperlane')||path.includes('/routes'))return <div className="card" style={{marginTop:18}}><h3>Decision transport</h3><div className="timeline"><div className="event">StudioNet finalized decision</div><div className="event">PRAEST verifies DecisionOutbox payload</div><div className="event">zkSync Sepolia gateway dispatches Hyperlane message</div><div className="event">Destination Mailbox + ISM verify</div><div className="event">Local escrow executes and PRAEST reconciles proof</div></div></div>;if(path.includes('genlayer')||path.includes('adjudication'))return <div className="card" style={{marginTop:18}}><h3>Finality rule</h3><p className="muted">ACCEPTED is provisional. PRAEST authorizes cross-chain settlement only after the appeal window and GenLayer FINALIZED state.</p></div>;return null}
