import {execFileSync} from "node:child_process";
import {existsSync,readdirSync,readFileSync,statSync,writeFileSync,mkdirSync} from "node:fs";
import path from "node:path";
import {createRequire} from "node:module";
const root=process.cwd(),failures=[],warnings=[],passes=[];
const required=["README.md","docs/ARCHITECTURE.md","docs/TRUST_MODEL.md","docs/SECURITY.md","docs/DEPLOYMENT.md","docs/HANDOFF.md","docs/IMPLEMENTATION_STATUS.md","docs/REQUIREMENTS_TRACEABILITY.md","packages/config/src/routes.json","packages/config/src/chains.json","contracts/genlayer/DecisionOutbox.py","contracts/evm/src/PraestSettlementReceiver.sol","contracts/solana/src/lib.rs","apps/api/src/lifecycle.ts","apps/bridge/src/main.ts","apps/probe/src/index.ts"];
for(const f of required)if(!existsSync(path.join(root,f)))failures.push(`missing ${f}`);else passes.push(`present ${f}`);
const sourceFiles=[];
function walk(dir){for(const e of readdirSync(dir)){if(["node_modules",".git","dist",".next","__pycache__","out","target"].includes(e))continue;const p=path.join(dir,e),st=statSync(p);if(st.isDirectory())walk(p);else if(/\.(ts|tsx|js|mjs|py|sol|rs|json|md|ya?ml|tf|toml)$/.test(e)){sourceFiles.push(p);const t=readFileSync(p,"utf8");if(/py-genlayer:(?:test|latest)(?:"|\s|$)/.test(t))failures.push(`unpinned GenLayer runner ${p}`);if(/verify\s*\([^)]*\)[\s\S]{0,180}return\s+true/.test(t)&&p.endsWith(".sol")&&!p.includes(`${path.sep}test${path.sep}`))failures.push(`permissive production ISM verify ${p}`);if(/TODO:\s*implement|throw new Error\(["']not implemented/i.test(t))failures.push(`implementation placeholder ${p}`);}}
}walk(root);
for(const f of ["package.json","apps/api/package.json","apps/web/package.json","packages/config/src/routes.json","packages/config/src/chains.json"]){try{JSON.parse(readFileSync(f,"utf8"));passes.push(`valid JSON ${f}`)}catch(e){failures.push(`invalid JSON ${f}: ${e.message}`)}}
const routes=JSON.parse(readFileSync("packages/config/src/routes.json","utf8"));const routeCounts=Object.fromEntries(Object.entries(routes).map(([k,v])=>[k,v.length]));const total=Object.values(routeCounts).reduce((a,b)=>a+b,0);if(total<150)failures.push(`route manifest unexpectedly small: ${total}`);else passes.push(`route manifest ${total} URLs`);for(const k of ["product","control","developer","explorer"])if(!routeCounts[k])failures.push(`route surface missing ${k}`);
try{execFileSync("python3",["-m","py_compile",...readdirSync("contracts/genlayer").filter(x=>x.endsWith(".py")).map(x=>`contracts/genlayer/${x}`)],{stdio:"pipe"});passes.push("GenLayer Python syntax")}catch(e){failures.push("GenLayer Python syntax failed")}
// Parser-level TS/TSX validation works even when workspace dependencies cannot be installed here.
try{const require=createRequire(import.meta.url);let ts;try{ts=require("typescript")}catch{ts=require("/opt/nvm/versions/node/v22.16.0/lib/node_modules/typescript")};for(const f of sourceFiles.filter(f=>/\.tsx?$/.test(f)&&!f.endsWith(".d.ts"))){const r=ts.transpileModule(readFileSync(f,"utf8"),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX},reportDiagnostics:true,fileName:f});const ds=(r.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error);if(ds.length)failures.push(`TypeScript syntax ${f}: ${ds.map(d=>ts.flattenDiagnosticMessageText(d.messageText," ")).join("; ")}`)}passes.push("TypeScript/TSX parser syntax")}catch(e){warnings.push(`TypeScript parser check unavailable: ${e.message}`)}
if(existsSync("node_modules/typescript")){try{execFileSync("npm",["run","typecheck"],{stdio:"inherit",shell:process.platform==="win32"});passes.push("dependency-resolved TypeScript typecheck")}catch{failures.push("TypeScript typecheck failed")}}else warnings.push("node_modules unavailable: dependency-resolved TypeScript typecheck not executed");
for(const [tool,args,cwd,label] of [["forge",["test","-q"],"contracts/evm","Foundry tests"],["cargo",["check","--manifest-path","contracts/solana/Cargo.toml"],root,"Solana cargo check"]]){try{execFileSync(tool,args,{cwd,stdio:"pipe",shell:process.platform==="win32"});passes.push(label)}catch(e){if(e?.code==="ENOENT")warnings.push(`${label} not executed: ${tool} unavailable`);else failures.push(`${label} failed`)}}
mkdirSync("verification",{recursive:true});const report={generatedAt:new Date().toISOString(),passes,warnings,failures,routeCounts,totalRoutes:total,fileCount:sourceFiles.length};writeFileSync("verification/static-report.json",JSON.stringify(report,null,2));
for(const p of passes)console.log(`✓ ${p}`);for(const w of warnings)console.warn(`! ${w}`);for(const f of failures)console.error(`✗ ${f}`);if(failures.length)process.exit(1);console.log(`✓ repository static verification passed (${warnings.length} warnings)`);
