import {pgTable,pgEnum,uuid,text,timestamp,jsonb,boolean,integer,bigint,numeric,primaryKey,uniqueIndex,index} from "drizzle-orm/pg-core";

const id=()=>uuid("id").primaryKey().defaultRandom();
const org=()=>uuid("organization_id").notNull().references(()=>organizations.id,{onDelete:"cascade"});
const created=()=>timestamp("created_at",{withTimezone:true}).notNull().defaultNow();
const updated=()=>timestamp("updated_at",{withTimezone:true}).notNull().defaultNow();

export const serviceStatus=pgEnum("service_status",["draft","active","paused","archived"]);
export const agreementStatus=pgEnum("agreement_status",["draft","active","suspended","terminated","completed"]);
export const monitorStatus=pgEnum("monitor_status",["active","paused","error"]);
export const incidentStatus=pgEnum("incident_status",["open","recovering","resolved","unknown"]);
export const caseStatus=pgEnum("case_status",["open","evidence_locked","submitted","decided","appealable","appealed","finalized","settling","settled","closed","undetermined"]);
export const adjudicationStatus=pgEnum("adjudication_status",["submitted","pending","proposing","committing","revealing","accepted","appealable","appealed","ready_to_finalize","finalized","undetermined","failed","canceled"]);
export const settlementStatus=pgEnum("settlement_status",["draft","authorized","dispatched","delivered","executing","executed","reconciling","settled","expired","failed"]);
export const protocolKind=pgEnum("protocol_kind",["ethereum","sealevel"]);

export const organizations=pgTable("organizations",{id:id(),workosOrganizationId:text("workos_organization_id").unique(),name:text("name").notNull(),slug:text("slug").notNull().unique(),settings:jsonb("settings").notNull().default({}),createdAt:created(),updatedAt:updated()});
export const users=pgTable("users",{id:id(),workosUserId:text("workos_user_id").notNull().unique(),email:text("email").notNull(),displayName:text("display_name"),privyUserId:text("privy_user_id"),createdAt:created(),updatedAt:updated()});
export const memberships=pgTable("memberships",{organizationId:uuid("organization_id").notNull().references(()=>organizations.id,{onDelete:"cascade"}),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),role:text("role").notNull().default("member"),permissions:jsonb("permissions").notNull().default([]),createdAt:created() },t=>[primaryKey({columns:[t.organizationId,t.userId]})]);
export const wallets=pgTable("wallets",{id:id(),organizationId:org(),userId:uuid("user_id").references(()=>users.id,{onDelete:"set null"}),ownerType:text("owner_type").notNull(),ownerId:uuid("owner_id"),chainFamily:text("chain_family").notNull(),address:text("address").notNull(),provider:text("provider").notNull(),purpose:text("purpose").notNull().default("general"),verifiedAt:timestamp("verified_at",{withTimezone:true}),createdAt:created()},t=>[uniqueIndex("wallet_org_addr_uq").on(t.organizationId,t.chainFamily,t.address)]);
export const walletChallenges=pgTable("wallet_challenges",{id:id(),organizationId:org(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),chainFamily:text("chain_family").notNull(),address:text("address").notNull(),nonce:text("nonce").notNull(),message:text("message").notNull(),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),consumedAt:timestamp("consumed_at",{withTimezone:true}),createdAt:created()});
export const apiKeys=pgTable("api_keys",{id:id(),organizationId:org(),name:text("name").notNull(),prefix:text("prefix").notNull(),secretHash:text("secret_hash").notNull(),permissions:jsonb("permissions").notNull().default([]),lastUsedAt:timestamp("last_used_at",{withTimezone:true}),revokedAt:timestamp("revoked_at",{withTimezone:true}),createdAt:created()});

export const services=pgTable("services",{id:id(),organizationId:org(),name:text("name").notNull(),kind:text("kind").notNull().default("api"),description:text("description"),status:serviceStatus("status").notNull().default("draft"),visibility:text("visibility").notNull().default("private"),baseUrl:text("base_url"),statusPageUrl:text("status_page_url"),documentationUrl:text("documentation_url"),metadata:jsonb("metadata").notNull().default({}),createdAt:created(),updatedAt:updated()},t=>[index("services_org_idx").on(t.organizationId)]);
export const serviceCredentials=pgTable("service_credentials",{id:id(),organizationId:org(),serviceId:uuid("service_id").notNull().references(()=>services.id,{onDelete:"cascade"}),name:text("name").notNull(),kind:text("kind").notNull(),ciphertext:text("ciphertext").notNull(),keyVersion:integer("key_version").notNull().default(1),rotatedAt:timestamp("rotated_at",{withTimezone:true}),createdAt:created(),updatedAt:updated()});
export const agents=pgTable("agents",{id:id(),organizationId:org(),name:text("name").notNull(),operatorUserId:uuid("operator_user_id").references(()=>users.id,{onDelete:"set null"}),description:text("description"),capabilities:jsonb("capabilities").notNull().default([]),authorityPolicy:jsonb("authority_policy").notNull().default({}),status:text("status").notNull().default("active"),createdAt:created(),updatedAt:updated()});
export const agentTasks=pgTable("agent_tasks",{id:id(),organizationId:org(),agentId:uuid("agent_id").notNull().references(()=>agents.id,{onDelete:"cascade"}),agreementId:uuid("agreement_id"),title:text("title").notNull(),input:jsonb("input").notNull().default({}),deliverableHash:text("deliverable_hash"),status:text("status").notNull().default("pending"),acceptedAt:timestamp("accepted_at",{withTimezone:true}),completedAt:timestamp("completed_at",{withTimezone:true}),createdAt:created()});
export const agentExecutionReceipts=pgTable("agent_execution_receipts",{id:id(),organizationId:org(),taskId:uuid("task_id").notNull().references(()=>agentTasks.id,{onDelete:"cascade"}),receiptType:text("receipt_type").notNull(),payload:jsonb("payload").notNull(),payloadHash:text("payload_hash").notNull(),signature:text("signature"),createdAt:created()});

export const agreements=pgTable("agreements",{id:id(),organizationId:org(),serviceId:uuid("service_id").references(()=>services.id,{onDelete:"set null"}),agentId:uuid("agent_id").references(()=>agents.id,{onDelete:"set null"}),name:text("name").notNull(),kind:text("kind").notNull(),status:agreementStatus("status").notNull().default("draft"),currentVersion:integer("current_version").notNull().default(1),settlementRouteKey:text("settlement_route_key"),settlementAsset:text("settlement_asset"),governedValue:numeric("governed_value",{precision:78,scale:0}),metadata:jsonb("metadata").notNull().default({}),createdAt:created(),updatedAt:updated()},t=>[index("agreements_org_idx").on(t.organizationId)]);
export const agreementVersions=pgTable("agreement_versions",{id:id(),organizationId:org(),agreementId:uuid("agreement_id").notNull().references(()=>agreements.id,{onDelete:"cascade"}),version:integer("version").notNull(),terms:jsonb("terms").notNull(),termsHash:text("terms_hash").notNull(),policyVersion:integer("policy_version").notNull().default(1),effectiveAt:timestamp("effective_at",{withTimezone:true}),createdAt:created()},t=>[uniqueIndex("agreement_version_uq").on(t.agreementId,t.version)]);
export const agreementParties=pgTable("agreement_parties",{id:id(),organizationId:org(),agreementId:uuid("agreement_id").notNull().references(()=>agreements.id,{onDelete:"cascade"}),partyType:text("party_type").notNull(),partyId:text("party_id").notNull(),role:text("role").notNull(),settlementAddress:text("settlement_address").notNull(),acceptedVersion:integer("accepted_version"),acceptedAt:timestamp("accepted_at",{withTimezone:true}),signature:text("signature")});

export const monitors=pgTable("monitors",{id:id(),organizationId:org(),serviceId:uuid("service_id").notNull().references(()=>services.id,{onDelete:"cascade"}),name:text("name").notNull(),url:text("url").notNull(),method:text("method").notNull().default("GET"),intervalSeconds:integer("interval_seconds").notNull(),timeoutMs:integer("timeout_ms").notNull(),regions:jsonb("regions").notNull().default([]),assertions:jsonb("assertions").notNull().default({}),credentialId:uuid("credential_id").references(()=>serviceCredentials.id,{onDelete:"set null"}),status:monitorStatus("status").notNull().default("active"),createdAt:created(),updatedAt:updated()});
export const incidents=pgTable("incidents",{id:id(),organizationId:org(),serviceId:uuid("service_id").notNull().references(()=>services.id,{onDelete:"cascade"}),monitorId:uuid("monitor_id").references(()=>monitors.id,{onDelete:"set null"}),status:incidentStatus("status").notNull().default("open"),classification:text("classification").notNull(),severity:text("severity").notNull().default("minor"),startedAt:timestamp("started_at",{withTimezone:true}).notNull(),recoveredAt:timestamp("recovered_at",{withTimezone:true}),summary:text("summary"),metadata:jsonb("metadata").notNull().default({}),createdAt:created(),updatedAt:updated()});

export const evidence=pgTable("evidence",{id:id(),organizationId:org(),agreementId:uuid("agreement_id").notNull().references(()=>agreements.id,{onDelete:"cascade"}),caseId:uuid("case_id"),kind:text("kind").notNull(),source:text("source").notNull(),provenance:jsonb("provenance").notNull(),objectKey:text("object_key"),sha256:text("sha256").notNull(),contentType:text("content_type"),sizeBytes:bigint("size_bytes",{mode:"bigint"}),verificationStatus:text("verification_status").notNull().default("unverified"),redactionPolicy:jsonb("redaction_policy").notNull().default({}),observedAt:timestamp("observed_at",{withTimezone:true}),createdAt:created()});
export const evidenceBundles=pgTable("evidence_bundles",{id:id(),organizationId:org(),agreementId:uuid("agreement_id").notNull().references(()=>agreements.id,{onDelete:"cascade"}),manifest:jsonb("manifest").notNull(),manifestHash:text("manifest_hash").notNull(),lockedAt:timestamp("locked_at",{withTimezone:true}),createdAt:created()});
export const evidenceBundleItems=pgTable("evidence_bundle_items",{bundleId:uuid("bundle_id").notNull().references(()=>evidenceBundles.id,{onDelete:"cascade"}),evidenceId:uuid("evidence_id").notNull().references(()=>evidence.id,{onDelete:"cascade"}),ordinal:integer("ordinal").notNull()},t=>[primaryKey({columns:[t.bundleId,t.evidenceId]})]);
export const tlsProofs=pgTable("tls_proofs",{id:id(),organizationId:org(),evidenceId:uuid("evidence_id").notNull().references(()=>evidence.id,{onDelete:"cascade"}),proofObjectKey:text("proof_object_key").notNull(),proofHash:text("proof_hash").notNull(),verifierVersion:text("verifier_version").notNull(),disclosureManifest:jsonb("disclosure_manifest").notNull().default({}),verifiedAt:timestamp("verified_at",{withTimezone:true}),createdAt:created()});

export const cases=pgTable("cases",{id:id(),organizationId:org(),agreementId:uuid("agreement_id").notNull().references(()=>agreements.id,{onDelete:"cascade"}),caseType:text("case_type").notNull(),status:caseStatus("status").notNull().default("open"),claim:text("claim").notNull(),requestedOutcome:text("requested_outcome"),evidenceBundleId:uuid("evidence_bundle_id").references(()=>evidenceBundles.id,{onDelete:"set null"}),openedBy:text("opened_by").notNull(),createdAt:created(),updatedAt:updated()},t=>[index("cases_org_idx").on(t.organizationId)]);
export const disputes=pgTable("disputes",{id:id(),organizationId:org(),caseId:uuid("case_id").notNull().references(()=>cases.id,{onDelete:"cascade"}).unique(),claimantStatement:text("claimant_statement"),respondentStatement:text("respondent_statement"),counterclaim:text("counterclaim"),responseDueAt:timestamp("response_due_at",{withTimezone:true}),evidenceLockedAt:timestamp("evidence_locked_at",{withTimezone:true}),createdAt:created(),updatedAt:updated()});
export const adjudications=pgTable("adjudications",{id:id(),organizationId:org(),caseId:uuid("case_id").notNull().references(()=>cases.id,{onDelete:"cascade"}),resolverKey:text("resolver_key").notNull(),genlayerContract:text("genlayer_contract").notNull(),genlayerTxHash:text("genlayer_tx_hash"),status:adjudicationStatus("status").notNull().default("submitted"),acceptedAt:timestamp("accepted_at",{withTimezone:true}),appealDeadline:timestamp("appeal_deadline",{withTimezone:true}),finalizedAt:timestamp("finalized_at",{withTimezone:true}),executionResult:text("execution_result"),rawDecision:jsonb("raw_decision"),createdAt:created(),updatedAt:updated()});
export const appeals=pgTable("appeals",{id:id(),organizationId:org(),adjudicationId:uuid("adjudication_id").notNull().references(()=>adjudications.id,{onDelete:"cascade"}),round:integer("round").notNull(),reason:text("reason").notNull(),newEvidenceBundleId:uuid("new_evidence_bundle_id").references(()=>evidenceBundles.id,{onDelete:"set null"}),genlayerTxHash:text("genlayer_tx_hash"),status:text("status").notNull().default("submitted"),createdAt:created()});
export const decisions=pgTable("decisions",{id:id(),organizationId:org(),caseId:uuid("case_id").notNull().references(()=>cases.id,{onDelete:"cascade"}),adjudicationId:uuid("adjudication_id").notNull().references(()=>adjudications.id,{onDelete:"cascade"}),decisionHash:text("decision_hash").notNull().unique(),outcome:text("outcome").notNull(),reasonCode:text("reason_code").notNull(),remedyBps:integer("remedy_bps").notNull().default(0),liability:jsonb("liability").notNull().default([]),finalizedAt:timestamp("finalized_at",{withTimezone:true}).notNull(),evidenceManifestHash:text("evidence_manifest_hash").notNull(),policyVersion:integer("policy_version").notNull(),createdAt:created()});

export const chainRoutes=pgTable("chain_routes",{id:id(),key:text("key").notNull().unique(),displayName:text("display_name").notNull(),protocol:protocolKind("protocol").notNull(),chainId:text("chain_id").notNull(),domainId:integer("domain_id").notNull(),mailbox:text("mailbox").notNull(),ism:text("ism"),receiver:text("receiver"),escrowContract:text("escrow_contract"),rpcEnv:text("rpc_env").notNull(),explorer:text("explorer"),enabled:boolean("enabled").notNull().default(true),metadata:jsonb("metadata").notNull().default({}),lastHealthCheck:timestamp("last_health_check",{withTimezone:true}),createdAt:created(),updatedAt:updated()});
export const escrows=pgTable("escrows",{id:id(),organizationId:org(),agreementId:uuid("agreement_id").notNull().references(()=>agreements.id,{onDelete:"cascade"}),routeKey:text("route_key").notNull(),asset:text("asset").notNull(),assetDecimals:integer("asset_decimals").notNull(),payerAddress:text("payer_address").notNull(),providerAddress:text("provider_address").notNull(),customerAddress:text("customer_address").notNull(),maxCustomerRemedyBps:integer("max_customer_remedy_bps").notNull().default(10000),amount:numeric("amount",{precision:78,scale:0}).notNull(),remainingAmount:numeric("remaining_amount",{precision:78,scale:0}).notNull(),status:text("status").notNull().default("created"),onchainEscrowId:text("onchain_escrow_id").notNull(),fundingTxHash:text("funding_tx_hash"),fundedAt:timestamp("funded_at",{withTimezone:true}),createdAt:created(),updatedAt:updated()});
export const settlementInstructions=pgTable("settlement_instructions",{id:id(),organizationId:org(),decisionId:uuid("decision_id").notNull().references(()=>decisions.id,{onDelete:"cascade"}),escrowId:uuid("escrow_id").notNull().references(()=>escrows.id,{onDelete:"restrict"}),instructionId:text("instruction_id").notNull().unique(),payload:jsonb("payload").notNull(),payloadHex:text("payload_hex").notNull(),payloadSha256:text("payload_sha256").notNull(),destinationDomain:integer("destination_domain").notNull(),status:settlementStatus("status").notNull().default("draft"),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),createdAt:created(),updatedAt:updated()});
export const hyperlaneMessages=pgTable("hyperlane_messages",{id:id(),organizationId:org(),instructionId:text("instruction_id").notNull().references(()=>settlementInstructions.instructionId,{onDelete:"cascade"}),messageId:text("message_id").unique(),originDomain:integer("origin_domain").notNull(),destinationDomain:integer("destination_domain").notNull(),dispatchTxHash:text("dispatch_tx_hash"),processTxHash:text("process_tx_hash"),deliveryStatus:text("delivery_status").notNull().default("pending"),destinationExecutionTxHash:text("destination_execution_tx_hash"),destinationStateHash:text("destination_state_hash"),lastCheckedAt:timestamp("last_checked_at",{withTimezone:true}),createdAt:created(),updatedAt:updated()});
export const receipts=pgTable("receipts",{id:id(),organizationId:org(),caseId:uuid("case_id").notNull().references(()=>cases.id,{onDelete:"restrict"}),decisionId:uuid("decision_id").notNull().references(()=>decisions.id,{onDelete:"restrict"}),instructionId:text("instruction_id").notNull().references(()=>settlementInstructions.instructionId,{onDelete:"restrict"}),receiptHash:text("receipt_hash").notNull().unique(),publicPayload:jsonb("public_payload").notNull(),createdAt:created()});

export const x402Requests=pgTable("x402_requests",{id:id(),organizationId:org(),serviceId:uuid("service_id").references(()=>services.id,{onDelete:"set null"}),agentId:uuid("agent_id").references(()=>agents.id,{onDelete:"set null"}),requestId:text("request_id").notNull().unique(),network:text("network").notNull(),scheme:text("scheme").notNull(),paymentPayload:jsonb("payment_payload").notNull(),paymentReceipt:jsonb("payment_receipt"),obligation:jsonb("obligation").notNull(),status:text("status").notNull().default("created"),createdAt:created(),updatedAt:updated()});
export const webhooks=pgTable("webhooks",{id:id(),organizationId:org(),url:text("url").notNull(),events:jsonb("events").notNull().default([]),secretCiphertext:text("secret_ciphertext").notNull(),enabled:boolean("enabled").notNull().default(true),createdAt:created(),updatedAt:updated()});
export const webhookDeliveries=pgTable("webhook_deliveries",{id:id(),organizationId:org(),webhookId:uuid("webhook_id").notNull().references(()=>webhooks.id,{onDelete:"cascade"}),eventType:text("event_type").notNull(),eventId:text("event_id").notNull(),payload:jsonb("payload").notNull(),attempt:integer("attempt").notNull().default(0),status:text("status").notNull().default("pending"),nextAttemptAt:timestamp("next_attempt_at",{withTimezone:true}),lastError:text("last_error"),deliveredAt:timestamp("delivered_at",{withTimezone:true}),createdAt:created()});
export const integrations=pgTable("integrations",{id:id(),organizationId:org(),kind:text("kind").notNull(),name:text("name").notNull(),configCiphertext:text("config_ciphertext").notNull(),status:text("status").notNull().default("active"),createdAt:created(),updatedAt:updated()});
export const notificationPreferences=pgTable("notification_preferences",{id:id(),organizationId:org(),userId:uuid("user_id").references(()=>users.id,{onDelete:"cascade"}),channels:jsonb("channels").notNull().default({email:true,inApp:true}),events:jsonb("events").notNull().default([]),createdAt:created(),updatedAt:updated()});
export const notifications=pgTable("notifications",{id:id(),organizationId:org(),userId:uuid("user_id").references(()=>users.id,{onDelete:"cascade"}),eventType:text("event_type").notNull(),title:text("title").notNull(),body:text("body").notNull(),metadata:jsonb("metadata").notNull().default({}),readAt:timestamp("read_at",{withTimezone:true}),createdAt:created()});

export const billingAccounts=pgTable("billing_accounts",{id:id(),organizationId:org().unique(),stripeCustomerId:text("stripe_customer_id").unique(),plan:text("plan").notNull().default("starter"),status:text("status").notNull().default("inactive"),createdAt:created(),updatedAt:updated()});
export const billingSubscriptions=pgTable("billing_subscriptions",{id:id(),organizationId:org(),stripeSubscriptionId:text("stripe_subscription_id").notNull().unique(),stripePriceId:text("stripe_price_id").notNull(),status:text("status").notNull(),currentPeriodEnd:timestamp("current_period_end",{withTimezone:true}),createdAt:created(),updatedAt:updated()});
export const usageEvents=pgTable("usage_events",{id:id(),organizationId:org(),eventName:text("event_name").notNull(),quantity:bigint("quantity",{mode:"bigint"}).notNull(),idempotencyKey:text("idempotency_key").notNull().unique(),stripeEventIdentifier:text("stripe_event_identifier"),metadata:jsonb("metadata").notNull().default({}),createdAt:created()});
export const tvgLedger=pgTable("tvg_ledger",{id:id(),organizationId:org(),agreementId:uuid("agreement_id").references(()=>agreements.id,{onDelete:"set null"}),caseId:uuid("case_id").references(()=>cases.id,{onDelete:"set null"}),kind:text("kind").notNull(),asset:text("asset").notNull(),amount:numeric("amount",{precision:78,scale:0}).notNull(),routeKey:text("route_key"),dedupeKey:text("dedupe_key").notNull().unique(),createdAt:created()});
export const reputationEvents=pgTable("reputation_events",{id:id(),organizationId:org(),subjectType:text("subject_type").notNull(),subjectId:text("subject_id").notNull(),caseId:uuid("case_id").references(()=>cases.id,{onDelete:"set null"}),scoreDelta:integer("score_delta").notNull(),reason:text("reason").notNull(),finalized:boolean("finalized").notNull().default(false),createdAt:created()});
export const auditLogs=pgTable("audit_logs",{id:id(),organizationId:org(),actorType:text("actor_type").notNull(),actorId:text("actor_id").notNull(),action:text("action").notNull(),resourceType:text("resource_type").notNull(),resourceId:text("resource_id"),ip:text("ip"),metadata:jsonb("metadata").notNull().default({}),createdAt:created()});
